Updates 03 2023
Creme-de-la-Dev/trader-bot-discord pull request #1
Opened 2023-03-06 17:11 UTC by gchan26

Nesta Pull Request:

- [X] Adicionadas novas frases;
- [x] Removidas frases datadas.

2023-03-06 17:47 UTC, davisjr2000 requested changes

2023-03-06 17:47 UTC, davisjr2000 commented on traderbot.py
> +        if message.content =="maranhao":
Identação

2023-03-06 17:47 UTC, davisjr2000 commented on traderbot.py
> +    if message.content =="mungus" || "sus" || "among us" || "monguinho":
Esse código não é válido no Python. Você precisa verificar cada caso pra variável.
Ex:
```
  if name == 'Ale' || name == 'Lirou
```

2023-03-06 17:47 UTC, davisjr2000 commented on traderbot.py
> -        await client.send_message(message.channel, "chama o dave")
Fallen Angel

2023-03-06 17:58 UTC, gchan26 commented on traderbot.py
> +    if message.content =="mungus" || "sus" || "among us" || "monguinho":
![Uploading IMG_9325.jpeg…]()

2023-03-06 17:59 UTC, gchan26 commented on traderbot.py
> +        if message.content =="maranhao":
ih mosquei

2023-03-07 01:38 UTC, gchan26 commented
Neste Commit:

- [X] Organização comentada por categorias;
- [X] Removidos textos datados.

2023-03-07 01:43 UTC, gchan26 commented on traderbot.py
> -        await client.send_message(message.channel, "chama o dave")
Foda

2023-03-07 21:39 UTC, merged